-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Abre"
(
    "idCicloEscolar" character varying COLLATE pg_catalog."default" NOT NULL,
    "idGrupo" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "abrePk" PRIMARY KEY ("idCicloEscolar", "idGrupo")
);

CREATE TABLE IF NOT EXISTS public."Accede"
(
    "nombreRol" character varying COLLATE pg_catalog."default" NOT NULL,
    "idPrivilegio" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "accedePk" PRIMARY KEY ("nombreRol", "idPrivilegio")
);

CREATE TABLE IF NOT EXISTS public."Administrador"
(
    "idIVD" character varying COLLATE pg_catalog."default" NOT NULL,
    carrera character varying COLLATE pg_catalog."default",
    CONSTRAINT "administradorPk" PRIMARY KEY ("idIVD")
);

CREATE TABLE IF NOT EXISTS public."Alumno"
(
    matricula character varying COLLATE pg_catalog."default" NOT NULL,
    semestre character varying COLLATE pg_catalog."default",
    regular boolean,
    carrera character varying COLLATE pg_catalog."default",
    CONSTRAINT "alumnoPk" PRIMARY KEY (matricula)
);

CREATE TABLE IF NOT EXISTS public."CicloEscolar"
(
    "idCicloEscolar" character varying COLLATE pg_catalog."default" NOT NULL,
    "fechaInicio" date,
    "fechaFin" date,
    "inicioInscripcion" date,
    "finInscripcion" date,
    CONSTRAINT "cicloEscolarPk" PRIMARY KEY ("idCicloEscolar")
);

CREATE TABLE IF NOT EXISTS public."Disponible"
(
    "idCicloEscolar" character varying COLLATE pg_catalog."default" NOT NULL,
    "matriculaProfesor" character varying COLLATE pg_catalog."default" NOT NULL,
    lunes time without time zone[],
    martes time without time zone[],
    miercoles time without time zone[],
    jueves time without time zone[],
    viernes time without time zone[],
    CONSTRAINT "disponiblePk" PRIMARY KEY ("idCicloEscolar", "matriculaProfesor")
);

CREATE TABLE IF NOT EXISTS public."Enlista"
(
    "idGrupo" character varying COLLATE pg_catalog."default" NOT NULL,
    matricula character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "enlistaPk" PRIMARY KEY ("idGrupo", matricula)
);

CREATE TABLE IF NOT EXISTS public."Grupo"
(
    "idGrupo" character varying COLLATE pg_catalog."default" NOT NULL,
    "idMateria" character varying COLLATE pg_catalog."default",
    "matriculaProfesor" character varying COLLATE pg_catalog."default",
    "idSalon" character varying COLLATE pg_catalog."default",
    "lunesInicio" time without time zone,
    "lunesFin" time without time zone,
    "martesInicio" time without time zone,
    "martesFin" time without time zone,
    "miercolesInicio" time without time zone,
    "miercolesFin" time without time zone,
    "juevesInicio" time without time zone,
    "juevesFin" time without time zone,
    "viernesInicio" time without time zone,
    "viernesFin" time without time zone,
    CONSTRAINT "Grupo_pkey" PRIMARY KEY ("idGrupo")
);

CREATE TABLE IF NOT EXISTS public."Materia"
(
    "idMateria" character varying COLLATE pg_catalog."default" NOT NULL,
    "nombreMateria" character varying COLLATE pg_catalog."default",
    "idPlan" character varying COLLATE pg_catalog."default",
    creditos numeric,
    "horasProfesor" numeric,
    equipamiento character varying COLLATE pg_catalog."default",
    CONSTRAINT "materiaPk" PRIMARY KEY ("idMateria")
);

CREATE TABLE IF NOT EXISTS public."Ofrece"
(
    "idCicloEscolar" character varying COLLATE pg_catalog."default" NOT NULL,
    "idMateria" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "ofrecePk" PRIMARY KEY ("idCicloEscolar", "idMateria")
);

CREATE TABLE IF NOT EXISTS public."Plan"
(
    "idPlan" character varying COLLATE pg_catalog."default" NOT NULL,
    nombre character varying COLLATE pg_catalog."default",
    carrera character varying COLLATE pg_catalog."default",
    CONSTRAINT "planPk" PRIMARY KEY ("idPlan")
);

CREATE TABLE IF NOT EXISTS public."Privilegio"
(
    "idPrivilegio" character varying COLLATE pg_catalog."default" NOT NULL,
    nombre character varying COLLATE pg_catalog."default",
    CONSTRAINT "privilegioPk" PRIMARY KEY ("idPrivilegio")
);

CREATE TABLE IF NOT EXISTS public."Profesor"
(
    "matriculaProfesor" character varying COLLATE pg_catalog."default" NOT NULL,
    "nombreProfesor" character varying COLLATE pg_catalog."default",
    estatus character varying COLLATE pg_catalog."default",
    CONSTRAINT "profesorPk" PRIMARY KEY ("matriculaProfesor")
);

CREATE TABLE IF NOT EXISTS public."Requisito"
(
    "idMateria" character varying COLLATE pg_catalog."default" NOT NULL,
    requisito character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "requisitoPk" PRIMARY KEY ("idMateria", requisito)
);

CREATE TABLE IF NOT EXISTS public."Salon"
(
    "idSalon" character varying COLLATE pg_catalog."default" NOT NULL,
    cupo integer,
    descripcion character varying COLLATE pg_catalog."default",
    CONSTRAINT "salonPk" PRIMARY KEY ("idSalon")
);

CREATE TABLE IF NOT EXISTS public."SolicitaCambio"
(
    matricula character varying COLLATE pg_catalog."default" NOT NULL,
    "idMateria" character varying COLLATE pg_catalog."default" NOT NULL,
    resuelto boolean,
    descripcion character varying COLLATE pg_catalog."default",
    "fechaSolicitud" date,
    "fechaResolucion" date,
    CONSTRAINT "solicitaCambioPk" PRIMARY KEY (matricula, "idMateria")
);

CREATE TABLE IF NOT EXISTS public."Usuario"
(
    "idIVD" character varying COLLATE pg_catalog."default" NOT NULL,
    "nombreUsuario" character varying COLLATE pg_catalog."default",
    password character varying COLLATE pg_catalog."default",
    "correoInstitucional" character varying COLLATE pg_catalog."default",
    rol character varying COLLATE pg_catalog."default",
    CONSTRAINT "usuarioPk" PRIMARY KEY ("idIVD")
);

ALTER TABLE IF EXISTS public."Abre"
    ADD CONSTRAINT "abreFk" FOREIGN KEY ("idCicloEscolar")
    REFERENCES public."CicloEscolar" ("idCicloEscolar") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Abre"
    ADD CONSTRAINT "abreFk2" FOREIGN KEY ("idGrupo")
    REFERENCES public."Grupo" ("idGrupo") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Accede"
    ADD CONSTRAINT "accedeFk" FOREIGN KEY ("idPrivilegio")
    REFERENCES public."Privilegio" ("idPrivilegio") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Administrador"
    ADD CONSTRAINT "administradorFk" FOREIGN KEY ("idIVD")
    REFERENCES public."Usuario" ("idIVD") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "administradorPk"
    ON public."Administrador"("idIVD");


ALTER TABLE IF EXISTS public."Alumno"
    ADD CONSTRAINT "alumnoFk" FOREIGN KEY (matricula)
    REFERENCES public."Usuario" ("idIVD") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "alumnoPk"
    ON public."Alumno"(matricula);


ALTER TABLE IF EXISTS public."Disponible"
    ADD CONSTRAINT "disponibleFk" FOREIGN KEY ("idCicloEscolar")
    REFERENCES public."CicloEscolar" ("idCicloEscolar") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Disponible"
    ADD CONSTRAINT "disponibleFk2" FOREIGN KEY ("matriculaProfesor")
    REFERENCES public."Profesor" ("matriculaProfesor") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Enlista"
    ADD CONSTRAINT "enlistaFk" FOREIGN KEY ("idGrupo")
    REFERENCES public."Grupo" ("idGrupo") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Enlista"
    ADD CONSTRAINT "enlistaFk2" FOREIGN KEY (matricula)
    REFERENCES public."Alumno" (matricula) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Grupo"
    ADD CONSTRAINT "Grupo_idMateria_fkey" FOREIGN KEY ("idMateria")
    REFERENCES public."Materia" ("idMateria") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Grupo"
    ADD CONSTRAINT "Grupo_idSalon_fkey" FOREIGN KEY ("idSalon")
    REFERENCES public."Salon" ("idSalon") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Grupo"
    ADD CONSTRAINT "Grupo_matriculaProfesor_fkey" FOREIGN KEY ("matriculaProfesor")
    REFERENCES public."Profesor" ("matriculaProfesor") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Materia"
    ADD CONSTRAINT "materiaFk" FOREIGN KEY ("idPlan")
    REFERENCES public."Plan" ("idPlan") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Ofrece"
    ADD CONSTRAINT "ofreceFk" FOREIGN KEY ("idCicloEscolar")
    REFERENCES public."CicloEscolar" ("idCicloEscolar") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Ofrece"
    ADD CONSTRAINT "ofreceFk2" FOREIGN KEY ("idMateria")
    REFERENCES public."Materia" ("idMateria") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Requisito"
    ADD CONSTRAINT "materiaFk2" FOREIGN KEY (requisito)
    REFERENCES public."Materia" ("idMateria") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Requisito"
    ADD CONSTRAINT "requisitoFk" FOREIGN KEY ("idMateria")
    REFERENCES public."Materia" ("idMateria") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."SolicitaCambio"
    ADD CONSTRAINT "solicitaCambioFk" FOREIGN KEY (matricula)
    REFERENCES public."Alumno" (matricula) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."SolicitaCambio"
    ADD CONSTRAINT "solicitaCambioFk2" FOREIGN KEY ("idMateria")
    REFERENCES public."Materia" ("idMateria") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

END;