-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.abre
(
    id_ciclo_escolar text COLLATE pg_catalog."default" NOT NULL,
    id_grupo text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT abre_pk PRIMARY KEY (id_ciclo_escolar, id_grupo)
);

CREATE TABLE IF NOT EXISTS public.accede
(
    nombre_rol text COLLATE pg_catalog."default" NOT NULL,
    id_privilegio text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT accede_pk PRIMARY KEY (nombre_rol, id_privilegio)
);

CREATE TABLE IF NOT EXISTS public.administradores
(
    id_ivd text COLLATE pg_catalog."default" NOT NULL,
    carrera text COLLATE pg_catalog."default",
    CONSTRAINT adminsitradores_pk PRIMARY KEY (id_ivd)
);

CREATE TABLE IF NOT EXISTS public.alumnos
(
    matricula text COLLATE pg_catalog."default" NOT NULL,
    semestre text COLLATE pg_catalog."default",
    regular boolean,
    carrera text COLLATE pg_catalog."default",
    CONSTRAINT alumnos_pk PRIMARY KEY (matricula)
);

CREATE TABLE IF NOT EXISTS public.ciclos_escolares
(
    id_ciclo_escolar text COLLATE pg_catalog."default" NOT NULL,
    fecha_inicio date,
    fecha_fin date,
    inicio_inscripcion date,
    fin_inscripcion date,
    CONSTRAINT ciclos_escolares_pk PRIMARY KEY (id_ciclo_escolar)
);

CREATE TABLE IF NOT EXISTS public.disponible
(
    id_ciclo_escolar text COLLATE pg_catalog."default" NOT NULL,
    matricula_profesor text COLLATE pg_catalog."default" NOT NULL,
    lunes time without time zone[],
    martes time without time zone[],
    miercoles time without time zone[],
    jueves time without time zone[],
    viernes time without time zone[],
    CONSTRAINT disponible_pk PRIMARY KEY (id_ciclo_escolar, matricula_profesor)
);

CREATE TABLE IF NOT EXISTS public.enlista
(
    id_grupo text COLLATE pg_catalog."default" NOT NULL,
    matricula text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT enlista_pk PRIMARY KEY (id_grupo, matricula)
);

CREATE TABLE IF NOT EXISTS public.grupos
(
    id_grupo text COLLATE pg_catalog."default" NOT NULL,
    id_materia text COLLATE pg_catalog."default",
    matricula_profesor text COLLATE pg_catalog."default",
    id_salon text COLLATE pg_catalog."default",
    lunes_inicio time without time zone,
    lunes_fin time without time zone,
    martes_inicio time without time zone,
    martes_fin time without time zone,
    miercoles_inicio time without time zone,
    miercoles_fin time without time zone,
    jueves_inicio time without time zone,
    jueves_fin time without time zone,
    viernes_inicio time without time zone,
    viernes_fin time without time zone,
    CONSTRAINT grupos_pk PRIMARY KEY (id_grupo)
);

CREATE TABLE IF NOT EXISTS public.materias
(
    id_materia text COLLATE pg_catalog."default" NOT NULL,
    nombre_materia text COLLATE pg_catalog."default",
    id_plan text COLLATE pg_catalog."default",
    creditos integer,
    horas_profesor integer,
    equipamiento text COLLATE pg_catalog."default",
    CONSTRAINT materias_pk PRIMARY KEY (id_materia)
);

CREATE TABLE IF NOT EXISTS public.ofrece
(
    id_ciclo_escolar text COLLATE pg_catalog."default" NOT NULL,
    id_materia text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT ofrece_pk PRIMARY KEY (id_ciclo_escolar, id_materia)
);

CREATE TABLE IF NOT EXISTS public.planes
(
    id_plan text COLLATE pg_catalog."default" NOT NULL,
    nombre text COLLATE pg_catalog."default",
    carrera text COLLATE pg_catalog."default",
    CONSTRAINT planes_pk PRIMARY KEY (id_plan)
);

CREATE TABLE IF NOT EXISTS public.privilegios
(
    id_privilegio text COLLATE pg_catalog."default" NOT NULL,
    nombre text COLLATE pg_catalog."default",
    CONSTRAINT privilegios_pk PRIMARY KEY (id_privilegio)
);

CREATE TABLE IF NOT EXISTS public.profesores
(
    matricula_profesor text COLLATE pg_catalog."default" NOT NULL,
    nombre_profesor text COLLATE pg_catalog."default",
    estatus text COLLATE pg_catalog."default",
    CONSTRAINT profesores_pk PRIMARY KEY (matricula_profesor)
);

CREATE TABLE IF NOT EXISTS public.requisito
(
    id_materia text COLLATE pg_catalog."default" NOT NULL,
    requisito text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT materias_seriadas_pk PRIMARY KEY (id_materia, requisito)
);

CREATE TABLE IF NOT EXISTS public.salones
(
    id_salon text COLLATE pg_catalog."default" NOT NULL,
    cupo integer,
    descripcion text COLLATE pg_catalog."default",
    CONSTRAINT salon_pk PRIMARY KEY (id_salon)
);

CREATE TABLE IF NOT EXISTS public.solicitudes_cambio
(
    matricula text COLLATE pg_catalog."default" NOT NULL,
    id_materia text COLLATE pg_catalog."default" NOT NULL,
    resuelto boolean,
    descripcion text COLLATE pg_catalog."default",
    fecha_solicitud date,
    fecha_resolucion date,
    CONSTRAINT solicitudes_cambio_pk PRIMARY KEY (matricula, id_materia)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id_ivd text COLLATE pg_catalog."default" NOT NULL,
    nombre_usuario text COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default",
    correo_institucional text COLLATE pg_catalog."default",
    rol text COLLATE pg_catalog."default",
    CONSTRAINT usuarios_pk PRIMARY KEY (id_ivd)
);

ALTER TABLE IF EXISTS public.abre
    ADD CONSTRAINT abre_fk FOREIGN KEY (id_ciclo_escolar)
    REFERENCES public.ciclos_escolares (id_ciclo_escolar) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.abre
    ADD CONSTRAINT abre_fk_2 FOREIGN KEY (id_grupo)
    REFERENCES public.grupos (id_grupo) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.accede
    ADD CONSTRAINT accede_fk FOREIGN KEY (id_privilegio)
    REFERENCES public.privilegios (id_privilegio) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.administradores
    ADD CONSTRAINT administrador_fk FOREIGN KEY (id_ivd)
    REFERENCES public.usuarios (id_ivd) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS adminsitradores_pk
    ON public.administradores(id_ivd);


ALTER TABLE IF EXISTS public.alumnos
    ADD CONSTRAINT alumno_fk FOREIGN KEY (matricula)
    REFERENCES public.usuarios (id_ivd) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS alumnos_pk
    ON public.alumnos(matricula);


ALTER TABLE IF EXISTS public.disponible
    ADD CONSTRAINT disponible_fk FOREIGN KEY (id_ciclo_escolar)
    REFERENCES public.ciclos_escolares (id_ciclo_escolar) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.disponible
    ADD CONSTRAINT disponible_fk_2 FOREIGN KEY (matricula_profesor)
    REFERENCES public.profesores (matricula_profesor) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.enlista
    ADD CONSTRAINT enlista_fk FOREIGN KEY (id_grupo)
    REFERENCES public.grupos (id_grupo) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.enlista
    ADD CONSTRAINT enlista_fk_2 FOREIGN KEY (matricula)
    REFERENCES public.alumnos (matricula) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.grupos
    ADD CONSTRAINT grupo_id_materia_fkey FOREIGN KEY (id_materia)
    REFERENCES public.materias (id_materia) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.grupos
    ADD CONSTRAINT grupo_id_salon_fkey FOREIGN KEY (id_salon)
    REFERENCES public.salones (id_salon) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.grupos
    ADD CONSTRAINT grupo_matricula_profesor_fkey FOREIGN KEY (matricula_profesor)
    REFERENCES public.profesores (matricula_profesor) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.materias
    ADD CONSTRAINT materias_fk FOREIGN KEY (id_plan)
    REFERENCES public.planes (id_plan) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ofrece
    ADD CONSTRAINT ofrece_fk FOREIGN KEY (id_ciclo_escolar)
    REFERENCES public.ciclos_escolares (id_ciclo_escolar) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ofrece
    ADD CONSTRAINT ofrece_fk_2 FOREIGN KEY (id_materia)
    REFERENCES public.materias (id_materia) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.requisito
    ADD CONSTRAINT materia_fk_2 FOREIGN KEY (requisito)
    REFERENCES public.materias (id_materia) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.requisito
    ADD CONSTRAINT requisito_fk FOREIGN KEY (id_materia)
    REFERENCES public.materias (id_materia) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.solicitudes_cambio
    ADD CONSTRAINT solicita_cambio_fk FOREIGN KEY (matricula)
    REFERENCES public.alumnos (matricula) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.solicitudes_cambio
    ADD CONSTRAINT solicita_cambio_fk2 FOREIGN KEY (id_materia)
    REFERENCES public.materias (id_materia) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

END;